### ISSUE TITLE
Library Assets Not Loading

### ISSUE THREAD

**Issue by Maruja101** [Poly-Haven/polyhavenassets#74]
Hi!, I recently purchased your addon on Blender Market, I followed the instructions you provided for Installation and even restarted Blender, the asset library showed up for Poly Haven, but it seems like there are only 5 that show up under models, I even tried revalidating the files but its only this 5 models shows up, can you please help me. also here it shows that I've downloaded the whole Library asset under Poly Haven
Thank you!

**Comment by Ramirez8052** [comment]
I have the same problem !

**Comment by gregzaal** [comment]
Hi, thanks for the catch. I've just pushed out a fix for this issue in v1.1.3 which you can update to from the add-on's user preferences.

**Comment by Ramirez8052** [comment]
Thanks for the feedback. But I just reinstalled addon but I only have the models. HDRI and Textures are still not displayed.

**Comment by Ramirez8052** [comment]
I've finally got everything in the Browser. I had to do a Revalidate Files and then do an Update on the Fetch Assets button.
